export const ADD_INGREDEINT = 'ADD_INGREDEINT';
export const REMOVE_INGREDEINT = 'REMOVE_INGREDEINT';
export const SET_INGREDEINTS = 'SET_INGREDEINT';
export const FATCH_INGREDIENTS_FAILED = 'FATCH_INGREDIENTS_FAILED';

export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START'
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHSE_BURGER_FAILED = 'PURCHSE_BURGER_FAILED'
export const PURCHASE_INIT = 'PURCHASE_INIT';
export const FATCH_ORDERS_START = 'FATCH_ORDERS_START';
export const FATCH_ORDERS_SUCCSESS= 'FATCH_ORDERS_SUCCSESS';
export const FATCH_ORDERS_FAIL = 'FATCH_ORDERS_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH'

